# Generated by Django 6.0.3 on 2026-03-21 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('science', 'Fan olimpiadalari'), ('sports', 'Sport musobaqalari'), ('contests', 'Tanlovlar')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('award', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('student', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(blank=True, max_length=200)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('medal', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(choices=[('Maktab', 'Maktab'), ('Shahar', 'Shahar'), ('Viloyat', 'Viloyat'), ('Respublika', 'Respublika'), ('Xalqaro', 'Xalqaro')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='Erkinov Ziyodullo', max_length=200)),
                ('category', models.CharField(choices=[("Ta'lim", "Ta'lim"), ('Maslahatlar', 'Maslahatlar'), ('Sport', 'Sport'), ('Tarbiya', 'Tarbiya'), ('Olimpiadalar', 'Olimpiadalar'), ('Yangiliklar', 'Yangiliklar')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('comments_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='director/')),
                ('message', models.TextField()),
                ('awards', models.TextField(help_text='Har bir award yangi qatorda')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GraduatingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=4)),
                ('total_students', models.IntegerField()),
                ('university_accepted', models.IntegerField()),
                ('honors', models.IntegerField()),
                ('abroad', models.IntegerField()),
                ('achievements', models.TextField(help_text='Har bir achievement yangi qatorda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('ebook', 'Elektron kitob'), ('textbook', 'Rasmiy darslik'), ('guide', "O'quv qo'llanma")], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('class_level', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('format', models.CharField(default='PDF', max_length=20)),
                ('file', models.FileField(upload_to='library/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/covers/')),
                ('downloads', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('established', models.IntegerField()),
                ('students_count', models.IntegerField()),
                ('teachers_count', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Har bir feature yangi qatorda yoziladi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/')),
                ('icon', models.CharField(default='Dumbbell', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('boys', "O'g'il bolalar"), ('girls', 'Qiz bolalar')], max_length=10)),
                ('age_group', models.CharField(max_length=50)),
                ('coach', models.CharField(blank=True, max_length=200)),
                ('achievements', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('experience', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Oliy toifali', 'Oliy toifali'), ('1-toifali', '1-toifali'), ('2-toifali', '2-toifali'), ('Yetakchi', 'Yetakchi')], max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('students_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.gallerycategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotableGraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('score', models.CharField(blank=True, max_length=100)),
                ('achievement', models.TextField(blank=True)),
                ('graduating_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notable_graduates', to='api.graduatingclass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
